engine:
  language:
    name: python
    version: 3.10.8
  package_manager:
    name: poetry
    version: 1.1.11
  additional_system_packages:
    - libmagic1

envs:
  POSTGRES_MAX_POOLSIZE: 5


server:
  replicas:
    _default: 1
    production: 2
  memory_limits: 256Mi
  requests:
    memory: 256Mi
    cpu: 256m
  envs:
    LOG_LEVEL: INFO
    POSTGRES_MAX_POOLSIZE: 10
    POSTGRES_PASSWORD: my-secret


cronjobs:
- command: python resend_messages.py
  concurrency: forbid
  enabled:
    _default: true
    sandbox: false
  name: resend
  schedule: "*/30 * * * *"

- command: python cleanup_tasks.py
  concurrency: forbid
  enabled: true
  name: cleanup-tasks
  schedule:
    _default: "* * * * *"
    dev: "0 1 * * *"

consumers:
- name: clickstream
  enabled: true
  command: python run_consumer.py clickstream
  replicas: 1
  envs:
    POSTGRES_MAX_POOLSIZE: 1
  memory_limits: 256Mi
  requests:
    memory: 256Mi
    cpu: 256m

db_migrations:
- command: alembic upgrade
  envs:
    POSTGRES_MAX_POOLSIZE: 1
secrets:
  POSTGRES_HOST:
    _default: postgres