language: {{ language }}
version: {{ version }}
additional_system_packages: {{ additional_system_packages }}
package_manager: {{ package_manager }}
package_manager_version: {{ package_manager_version }}