package config

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"gopkg.in/yaml.v3"
)

const generatedValuesHeader = "# GENERATED BY MANMAN. EDIT WITH CAUTION.\n\n"

// GenerateValuesFiles reads app.yaml and generates values files for every environment.
// If only _default overrides are present, it generates a single values.yaml file.
func GenerateValuesFiles(appPath string) ([]string, error) {
	data, err := os.ReadFile(appPath)
	if err != nil {
		return nil, fmt.Errorf("read manifest: %w", err)
	}

	var root any
	if err := yaml.Unmarshal(data, &root); err != nil {
		return nil, fmt.Errorf("unmarshal manifest yaml: %w", err)
	}

	normalized := normalizeYAMLValue(root)
	envs := collectEnvironments(normalized)
	outputDir := filepath.Dir(appPath)

	if len(envs) == 0 {
		content, err := yaml.Marshal(resolveValueForEnv(normalized, ""))
		if err != nil {
			return nil, fmt.Errorf("marshal values.yaml: %w", err)
		}

		output := filepath.Join(outputDir, "values.yaml")
		content = append([]byte(generatedValuesHeader), content...)
		if err := os.WriteFile(output, content, 0o644); err != nil {
			return nil, fmt.Errorf("write %s: %w", output, err)
		}
		return []string{output}, nil
	}

	files := make([]string, 0, len(envs))
	for _, env := range envs {
		content, err := yaml.Marshal(resolveValueForEnv(normalized, env))
		if err != nil {
			return nil, fmt.Errorf("marshal values.%s.yaml: %w", env, err)
		}

		output := filepath.Join(outputDir, fmt.Sprintf("values.%s.yaml", env))
		content = append([]byte(generatedValuesHeader), content...)
		if err := os.WriteFile(output, content, 0o644); err != nil {
			return nil, fmt.Errorf("write %s: %w", output, err)
		}
		files = append(files, output)
	}

	return files, nil
}

func collectEnvironments(value any) []string {
	set := map[string]struct{}{}
	collectEnvironmentsRecursive(value, set)

	out := make([]string, 0, len(set))
	for env := range set {
		out = append(out, env)
	}
	sort.Strings(out)
	return out
}

func collectEnvironmentsRecursive(value any, out map[string]struct{}) {
	switch typed := value.(type) {
	case map[string]any:
		if _, ok := typed["_default"]; ok {
			for key := range typed {
				if key == "_default" || key == "" || key[0] == '_' {
					continue
				}
				out[key] = struct{}{}
			}
		}
		for _, nested := range typed {
			collectEnvironmentsRecursive(nested, out)
		}
	case []any:
		for _, item := range typed {
			collectEnvironmentsRecursive(item, out)
		}
	}
}

func resolveValueForEnv(value any, env string) any {
	switch typed := value.(type) {
	case map[string]any:
		if _, ok := typed["_default"]; ok {
			if env != "" {
				if val, exists := typed[env]; exists {
					return resolveValueForEnv(val, env)
				}
			}
			return resolveValueForEnv(typed["_default"], env)
		}

		resolved := make(map[string]any, len(typed))
		for key, nested := range typed {
			resolved[key] = resolveValueForEnv(nested, env)
		}
		return resolved
	case []any:
		resolved := make([]any, len(typed))
		for i, item := range typed {
			resolved[i] = resolveValueForEnv(item, env)
		}
		return resolved
	default:
		return typed
	}
}

func normalizeYAMLValue(value any) any {
	switch typed := value.(type) {
	case map[string]any:
		out := make(map[string]any, len(typed))
		for key, nested := range typed {
			out[key] = normalizeYAMLValue(nested)
		}
		return out
	case map[any]any:
		out := make(map[string]any, len(typed))
		for key, nested := range typed {
			out[fmt.Sprint(key)] = normalizeYAMLValue(nested)
		}
		return out
	case []any:
		out := make([]any, len(typed))
		for i, item := range typed {
			out[i] = normalizeYAMLValue(item)
		}
		return out
	default:
		return typed
	}
}
